brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
namesrvAddr=rocketmq-namesrv:9876
# 本地 IDE 调试：brokerIP1=127.0.0.1 让宿主机 IDE 能连上 broker(10911 已映射)
# 全 docker 部署：改为 brokerIP1=rocketmq-broker 让容器内服务能互连
brokerIP1=127.0.0.1
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
