server:
  port: 8086

spring:
  application:
    name: gateway
  config:
    import: "nacos:common.yaml?group=DEFAULT_GROUP"
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.80.1:8848
      config:
        server-addr: 192.168.80.1:8848
    gateway:
      # 服务发现路由配置：通过服务名转发
      routes:
        # 登录服务
        - id: login-server
          uri: lb://login-server
          predicates:
            - Path=/api/login/**
        # 主服务（gym）所有接口
        - id: main-server-admin
          uri: lb://main-server
          predicates:
            - Path=/api/admin/**
        - id: main-server-member
          uri: lb://main-server
          predicates:
            - Path=/api/member/**
        - id: main-server-employee
          uri: lb://main-server
          predicates:
            - Path=/api/employee/**
        - id: main-server-equipment
          uri: lb://main-server
          predicates:
            - Path=/api/equipment/**
        - id: main-server-class
          uri: lb://main-server
          predicates:
            - Path=/api/class/**
        - id: main-server-order
          uri: lb://main-server
          predicates:
            - Path=/api/order/**
      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719
      eager: true
