server:
  port: 8084

spring:
  application:
    name: main-server
  config:
    import: "nacos:common.yaml?group=DEFAULT_GROUP"
  datasource:
    url: jdbc:mysql://localhost:3306/gym?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

mybatis:
  type-aliases-package: com.gym.entity
