server:
  port: 8085

spring:
  application:
    name: login-server
  config:
    import: "nacos:common.yaml?group=DEFAULT_GROUP"
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8720
  datasource:
    url: "jdbc:mysql://localhost:3307/gym?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
